### ISSUE TITLE
Install glitch extension vscodium

### ISSUE THREAD

**Issue by m3astwood** [vscode-glitch/vscode-glitch#26]
Are there instructions on how to install the glitch extension on VSCodium? The extension is not appearing in the extension 'store'.

**Comment by rodoviario** [comment]
In the [marketplace](https://marketplace.visualstudio.com/items?itemName=glitch.glitch) you can download the extension file (with a .vslx ending extension) located in the bottom-right area, below Resources 

![Download extension](https://user-images.githubusercontent.com/4974682/91415090-e6172f80-e823-11ea-87f5-9925c343470b.png)

and then drag and drop to vscodium extensions area. 

![Captura de pantalla -2020-08-27 05-07-59](https://user-images.githubusercontent.com/4974682/91415094-e7e0f300-e823-11ea-85be-7de391ae2d93.png)

**Comment by m3astwood** [comment]
Amazing, thanks for the help.
