### ISSUE TITLE
Glitch Project Files do not show in Explorer for some reason

### ISSUE THREAD

**Issue by NTMNathan** [vscode-glitch/vscode-glitch#3]
I understand the Glitch Extension hasn’t been out for long and is in beta but most of my Glitch projects can be opened with VSCode perfectly with everything but there is one project where I can open it but doesn’t display my files in the explorer sidebar and I have to use “Go To File cmd+p” to find my project files. The terminal and output show fine when I run Glitch: Console

<img width="1990" alt="Screen Shot 2019-07-09 at 11 15 35 pm" src="https://user-images.githubusercontent.com/34463340/60892363-66867400-a2a2-11e9-96c4-7309203f2608.png">
<img width="1991" alt="Screen Shot 2019-07-09 at 11 05 54 pm" src="https://user-images.githubusercontent.com/34463340/60892365-66867400-a2a2-11e9-8aaa-4acb9be85494.png">

Project Name: nate-bot

**Comment by dluxemburg** [comment]
Hello. There was a bug affecting file display in projects with non-text files. That's fixed now. Can you try again with the latest release?

**Comment by dluxemburg** [comment]
Closing. Other reports of this have been confirmed as fixed.
