### ISSUE TITLE
VS Code closes itself

### ISSUE THREAD

**Issue by tfo-dot** [vscode-glitch/vscode-glitch#4]
When I'm writing code my VS Code can crash with returning this error. This only hapens when I open glitch project. I'm using VS Code for windows but my friend who has linux version of VS Code gets the same error. This happens every ~30mins.

[My friends screnshot](https://media.discordapp.net/attachments/598475086693007361/599300782633779220/unknown.png)

**Comment by dluxemburg** [comment]
Hi. We think we've fixed this, so trying again with the latest version should work. Let us know if the issue isn't resolved now.
