### ISSUE TITLE
Debugging 

### ISSUE THREAD

**Issue by GabCores** [vscode-glitch/vscode-glitch#5]
Debugging is to working fine , debugger tool disappear when arriving at breakpoints .
Enable to see var contents in debugger instances .

**Comment by dluxemburg** [comment]
Hi. Are you using Windows? We know there are some issues with breakpoints, I'll update when we have a fix.

**Comment by GabCores** [comment]
Yes. Using Windows , ok keep waiting , no big problem , thanks
