### ISSUE TITLE
Is glitch.token a secret?

### ISSUE THREAD

**Issue by ithinkihaveacat** [vscode-glitch/vscode-glitch#6]
After installing the extension and logging in I have a `glitch.token` key (and value) in my `settings.json`. Can this be made public or is it a secret? (My VS Code configuration file is stored in [my public .dotfiles repo](https://github.com/ithinkihaveacat/dotfiles).)

**Comment by dluxemburg** [comment]
`glitch.token` should be kept private.

Sharing configuration files is an interesting case that we hadn't considered. We think we will eventually change the way authentication information is stored, but for now you will need to find a way to keep that information out of your shared files.

**Comment by ithinkihaveacat** [comment]
FWIW the `github.vscode-pull-request-github` extension uses something called [keytar](https://www.npmjs.com/package/keytar), which stores the credentials in an OS-specific keychain ([usage](https://github.com/microsoft/vscode-pull-request-github/blob/master/src/authentication/keychain.ts)).

**Comment by dluxemburg** [comment]
Thanks, that's a great suggestion. I'll take a closer look.
