### ISSUE TITLE
code editor cannot be opened

### ISSUE THREAD

**Issue by thesimg** [vscode-glitch/vscode-glitch#7]
Whenever I open or start a new project, it won't show the code and opens up a search bar and doesn't show the code editor. This happens to new projects I start from VSC and projects I had in glitch prior to the extension.
![vscglitchissue](https://user-images.githubusercontent.com/52168814/62826041-0aee2580-bb83-11e9-9e5b-18b91ccffe18.JPG)

**Comment by dluxemburg** [comment]
You should be able to switch to the file tree view by clicking on the icon directly above the highlighted search one on the far left of the window.

You can also select files to open from a drop down menu with the keyboard shortcut (CMD/CTRL+P).
